### ISSUE TITLE
error with GENCODE annotations

### ISSUE THREAD

**Issue by baishengjun** [comprna/R2Dtool#1]
Hi,

When using the R2_lift.R script with GENCODE annotation file, I encounter the error with transcript_id.
`Problem with transcript_id.
Backtrace:
 1. ├─... %>% mutate(score = ".", .after = metaname)
 2. ├─dplyr::mutate(., score = ".", .after = metaname)
 3. ├─dplyr::inner_join(mappedLocus, strand_lookup, by = "transcript_id")
 4. └─dplyr:::inner_join.data.frame(mappedLocus, strand_lookup, by = "transcript_id")
 5.   └─dplyr:::join_mutate(...)
 6.     └─dplyr:::join_cols(...)
 7.       └─dplyr:::standardise_join_by(...)
 8.         └─dplyr:::check_join_vars(by$x, x_names, error_call = error_call)
 9.           └─rlang::abort(bullets, call = error_call)
Execution halted
`
I follow your generate notes,  commenting out line 25 in lift.R and line 27 in annotate.R. But it seems update, does not corresponding with it. 
In addition, same error with test data.

Bai,
Thanks a lot

**Comment by pre-mRNA** [comment]
Hi Bai, if you'd like to share the GTF file, I can take a look.
