### ISSUE TITLE
Issue with CHEUI output conversion

### ISSUE THREAD

**Issue by gsukrit** [comprna/R2Dtool#2]
Hi team,

So I tried running the suggested R2Dtool. The CHEUI output file (site_level_5mC_prediction) looked like this:

![image](https://github.com/comprna/R2Dtool/assets/81628564/83e2bf37-33f1-445c-be4e-1d72f841515f)

The command bash cheui_to_bed.sh [cheui model II output file] [cheui_to_bed output file] created a file that looked like this:

![image](https://github.com/comprna/R2Dtool/assets/81628564/030e772e-2ea9-47a4-8446-a535a7979239)

For some reason it hasn;t copied the complete gene accession IDs. Probably the reason why Rscript ./scripts/R2_annotate.R ./test/out_CHEUI_modelII.bed ./test/GRCm39_subset.gtf ./test/out_CHEUI_modelII_annotated.bed gave the following error:

![image](https://github.com/comprna/R2Dtool/assets/81628564/f76a245a-31ce-48ed-8b85-44d5d6473894)

Please let me know what went wrong and how to proceed further. 

Thank you for your response and efforts,

Sukriti

**Comment by EduEyras** [comment]
Hi Sukriti,

It might be related to the format of the GTF file
AJ will be able to see the problem from the error message

best

Eduardo

**Comment by pre-mRNA** [comment]
Apologies for the error, which was related to handling underscore delimiters during generation of the input bed file for R2Dtool. Fixed as of [4f7a9c1](https://github.com/comprna/R2Dtool/commit/4f7a9c151205531abed549777141da0a7172e272)
